services:

  # Certbot (for certificate issuance and renewal)
  # This container is run once on demand.
  mcmp-certbot:
    image: certbot/certbot:latest
    container_name: mcmp-certbot
    ports:
      - "80:80"  # Port 80 is used in standalone mode
    volumes:
      # Stores Certbot config and issued certificates (read/write access required)
      - ./container-volume/mc-iam-manager/certs:/etc/letsencrypt
    environment:
      MC_IAM_MANAGER_PUBLIC_DOMAIN: ${MC_IAM_MANAGER_PUBLIC_DOMAIN}
      MC_IAM_MANAGER_CERT_EMAIL: ${MC_IAM_MANAGER_CERT_EMAIL}
    entrypoint: ["certbot"]
    #command: ["certonly", "--standalone", "--email", "${MC_IAM_MANAGER_CERT_EMAIL}", "--agree-tos", "--no-eff-email", "-d", "${MC_IAM_MANAGER_PUBLIC_DOMAIN}", "--non-interactive", "--staging"] # <-- test issuance
    command: ["certonly", "--standalone", "--email", "${MC_IAM_MANAGER_CERT_EMAIL}", "--agree-tos", "--no-eff-email", "-d", "${MC_IAM_MANAGER_PUBLIC_DOMAIN}", "--non-interactive"] # <-- actual issuance
    #command: ["certonly", "--standalone", "--email", "${MC_IAM_MANAGER_CERT_EMAIL}", "--agree-tos", "--no-eff-email", "-d", "${MC_IAM_MANAGER_PUBLIC_DOMAIN}", "--non-interactive", "--force-renewal"] # <-- force renewal